# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: true
dist: trusty

git:
  submodules: false

after_success:
  - Rscript -e 'covr::codecov()'
